// <auto-generated />
using BankListAPI.VsCode.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankListAPI.VsCode.Migrations
{
    [DbContext(typeof(BankListDbContext))]
    [Migration("20230425170321_SeededCountriesAndBanks")]
    partial class SeededCountriesAndBanks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankListAPI.VsCode.Data.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Trivandrum Kerala",
                            CountryId = 1,
                            Name = "HDFC Bank",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Leamingtion Spa",
                            CountryId = 2,
                            Name = "HSBC Bank",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Leamingtion Spa",
                            CountryId = 2,
                            Name = "Barclays",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Athani, India",
                            CountryId = 1,
                            Name = "SBI",
                            Rating = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("BankListAPI.VsCode.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "India",
                            ShortName = "IN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        });
                });

            modelBuilder.Entity("BankListAPI.VsCode.Data.Bank", b =>
                {
                    b.HasOne("BankListAPI.VsCode.Data.Country", "CountryName")
                        .WithMany("Banks")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryName");
                });

            modelBuilder.Entity("BankListAPI.VsCode.Data.Country", b =>
                {
                    b.Navigation("Banks");
                });
#pragma warning restore 612, 618
        }
    }
}
